const G_DATA = [
  { 
    id: '117', 
    n: "Cyberpunk 2077", 
    dev: "CD PROJEKT RED", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=117&name=Cyberpunk%202077", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_hero.jpg", 
    ach: 45, 
    tags: ["Cyberpunk", "Open World", "RPG", "Sci-fi"],
    desc: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a megalopolis obsessed with power, glamour, and body modification.",
    rm: { os: "Windows 10", cpu: "Intel Core i7-6700K", ram: "12 GB RAM", gpu: "GTX 1060 6GB" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-12700", ram: "16 GB RAM", gpu: "RTX 2060 SUPER" }
  },
  { 
    id: '209', 
    n: "Grand Theft Auto V", 
    dev: "Rockstar North", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=209", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_hero.jpg", 
    ach: 77, 
    tags: ["Open World", "Action", "Multiplayer", "Crime"],
    desc: "When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening elements of the criminal underworld.",
    rm: { os: "Windows 10 64 Bit", cpu: "Intel Core 2 Quad CPU", ram: "4 GB RAM", gpu: "NVIDIA 9800 GT 1GB" },
    rr: { os: "Windows 10 64 Bit", cpu: "Intel Core i5 3470", ram: "8 GB RAM", gpu: "NVIDIA GTX 660 2GB" }
  },
  { 
    id: '598', 
    n: "Elden Ring", 
    dev: "FromSoftware Inc.", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=598", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_hero.jpg", 
    ach: 42, 
    tags: ["Souls-like", "Dark Fantasy", "RPG", "Difficult"],
    desc: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    rm: { os: "Windows 10", cpu: "INTEL CORE I5-8400", ram: "12 GB RAM", gpu: "GTX 1060 3 GB" },
    rr: { os: "Windows 10/11", cpu: "INTEL CORE I7-8700K", ram: "16 GB RAM", gpu: "GTX 1070 8 GB" }
  },
  { 
    id: '1014', 
    n: "Sim Racing Telemetry - F1 22", 
    dev: "Codemasters", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1014&name=Sim%20Racing%20Telemetry%20-%20F1%2022", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1692250/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1692250/library_hero.jpg", 
    ach: 30, 
    tags: ["Racing", "Simulation", "Sports", "Formula 1"],
    desc: "Take your seat in the new era of Formula 1. Analyze deep telemetry and conquer the tracks of the 2022 FIA Formula One World Championship with unprecedented realism.",
    rm: { os: "Windows 10", cpu: "Intel Core i3-2130", ram: "8 GB RAM", gpu: "GTX 1050 Ti" },
    rr: { os: "Windows 10", cpu: "Intel Core i5 9600K", ram: "16 GB RAM", gpu: "GTX 1660 Ti" }
  },
  { 
    id: '1021', 
    n: "Little Nightmares III", 
    dev: "Supermassive Games", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1021&name=Little%20Nightmares%20III", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2136470/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2136470/library_hero.jpg", 
    ach: 25, 
    tags: ["Horror", "Puzzle", "Adventure", "Atmospheric"],
    desc: "Embark on a haunting cooperative journey. Navigate a surreal, disturbing world and face your deepest childhood fears to escape the Nowhere.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-8400", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 11", cpu: "Intel Core i7-9700", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '1018', 
    n: "SAND LAND", 
    dev: "ILCA, Inc.", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1018&name=SAND%20LAND", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1979440/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1979440/library_hero.jpg", 
    ach: 35, 
    tags: ["Action", "RPG", "Anime", "Open World"],
    desc: "Dive into a vast desert world where humans and demons suffer from extreme water shortages. Play as the Fiend Prince Beelzebub and lead a heroic misfit cast.",
    rm: { os: "Windows 10", cpu: "AMD FX-8350", ram: "4 GB RAM", gpu: "Radeon HD 7870" },
    rr: { os: "Windows 10", cpu: "Intel Core i5-9400", ram: "8 GB RAM", gpu: "GTX 1660" }
  },
  { 
    id: '1016', 
    n: "X-Plane 11", 
    dev: "Laminar Research", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1016&name=X-Plane%2011", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/269950/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/269950/library_hero.jpg", 
    ach: 0, 
    tags: ["Simulation", "Flight", "Realistic", "Open World"],
    desc: "Experience the ultimate in flight simulation. Featuring a highly detailed physics engine, pilot a massive variety of aircraft across a beautifully rendered globe.",
    rm: { os: "Windows 8", cpu: "Intel Core i3", ram: "8 GB RAM", gpu: "GTX 1050" },
    rr: { os: "Windows 10", cpu: "Intel Core i5 8600K", ram: "16 GB RAM", gpu: "GTX 1070" }
  },
   { 
    id: 'MC120', 
    n: "Minecraft 1.20 Browser (Eagler Craft)", 
    dev: "Some random dude", 
    url: "https://yee.pages.dev/#/bW9yZS9tb3JlL21vZGRlZC9lYWdseWpz",
    img: "https://cdn.mos.cms.futurecdn.net/AZ4nyhrARyZhc69hMXAy3L.jpg",
    bg: "https://cdn.mos.cms.futurecdn.net/AZ4nyhrARyZhc69hMXAy3L.jpg",
    ach: 45, 
    tags: ["Minecraft", "Open World", "RPG", "Sci-fi"],
    desc: "Minecraft is a critically acclaimed 3D sandbox video game developed by the Swedish studio Mojang Studios. It has no specific goals, offering players absolute freedom to explore, build, and craft. The game world is made of 3D blocks representing materials like dirt, stone, and wood.",
    rm: { os: "Potato", cpu: "Potato", ram: "Potato", gpu: "Potato" },
    rr: { os: "Monster", cpu: "Monster", ram: "Monster", gpu: "Monster" }
  },
  { 
    id: '1015', 
    n: "GUILTY GEAR -STRIVE-", 
    dev: "Arc System Works", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1015&name=GUILTY%20GEAR%20-STRIVE-", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1384160/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1384160/library_hero.jpg", 
    ach: 40, 
    tags: ["Fighting", "Action", "Anime", "2D"],
    desc: "Experience the cutting edge of 2D fighting games. With stunning cel-shaded visuals and an explosive heavy-metal soundtrack, prepare for intense, high-octane combat.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-3450", ram: "4 GB RAM", gpu: "GTX 650 Ti" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-3770", ram: "8 GB RAM", gpu: "GTX 660" }
  },
  { 
    id: '1013', 
    n: "Clair Obscur: Expedition 33", 
    dev: "Sandfall Interactive", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1013&name=Clair%20Obscur%3A%20Expedition%2033", 
    img: "https://cdn1.epicgames.com/spt-assets/330dace5ffc74156987f91d454ac544b/project-w-1kt2x.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2808040/library_hero.jpg", 
    ach: 20, 
    tags: ["RPG", "Turn-Based", "Fantasy", "Story Rich"],
    desc: "A breathtaking turn-based RPG with real-time mechanics. Join Expedition 33 and break the deadly cycle of the Paintress before she erases humanity.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-8400", ram: "12 GB RAM", gpu: "GTX 1070" },
    rr: { os: "Windows 11", cpu: "Intel Core i7-10700K", ram: "16 GB RAM", gpu: "RTX 3060" }
  },
  { 
    id: '1012', 
    n: "Easy Red 2", 
    dev: "Marco Amadei", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1012&name=Easy%20Red%202", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1325710/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1325710/library_hero.jpg", 
    ach: 30, 
    tags: ["Shooter", "WWII", "Action", "Simulation"],
    desc: "Experience the massive scale of World War II. Fight in historical battles with an emphasis on tactical realism, squad management, and massive maps.",
    rm: { os: "Windows 7", cpu: "Intel Core i3", ram: "4 GB RAM", gpu: "GTX 460" },
    rr: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 960" }
  },
  { 
    id: '1003', 
    n: "JDM: Japanese Drift Master", 
    dev: "Gaming Factory", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1003&name=JDM%3A%20Japanese%20Drift%20Master", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1153410/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1153410/library_hero.jpg", 
    ach: 15, 
    tags: ["Racing", "Drifting", "Automobile", "Simulation"],
    desc: "Discover the heart of Japanese automotive culture. Drift through beautifully recreated streets, tune your vehicles, and master the art of the perfect slide.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-4460", ram: "8 GB RAM", gpu: "GTX 1050" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-7700", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '1002', 
    n: "The First Berserker: Khazan", 
    dev: "Nexon", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1002&name=The%20First%20Berserker%3A%20Khazan", 
    img: "https://clouddosage.com/wp-content/uploads/2025/03/The-First-Berserker-Khazan-review-feature.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2161730/library_hero.jpg", 
    ach: 25, 
    tags: ["Action", "Hardcore", "RPG", "Fantasy"],
    desc: "Unleash your fury in this hardcore action RPG. Survive brutal combat encounters in a grim, dark fantasy world built around visceral hack-and-slash mechanics.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-8400", ram: "12 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 11", cpu: "Intel Core i7-10700", ram: "16 GB RAM", gpu: "RTX 2070" }
  },
  { 
    id: '1001', 
    n: "Blue Prince", 
    dev: "Dogubom Studio", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1001&name=Blue%20Prince", 
    img: "https://assets.nintendo.com/image/upload/q_auto/f_auto/store/software/switch2/70010000109038/b981f7ef5d2df071e77e83bbe6ded66110931ecdb62571ad2086d5523bf4af06", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1578380/library_hero.jpg", 
    ach: 10, 
    tags: ["Puzzle", "Strategy", "Indie", "Relaxing"],
    desc: "Step into an intricate puzzle strategy experience where your choices construct the very house you are exploring, uncovering mysteries room by room.",
    rm: { os: "Windows 10", cpu: "Intel Core i3", ram: "4 GB RAM", gpu: "Integrated Graphics" },
    rr: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 960" }
  },
  { 
    id: '999', 
    n: "Only Up", 
    dev: "SCKR Games", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=999&name=Only%20Up", 
    img: "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/07/only-up-can-you-save-the-game.jpg", 
    bg: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1920&h=1080&fit=crop", 
    ach: 5, 
    tags: ["Platformer", "Difficult", "3D", "Parkour"],
    desc: "Embark on a relentless vertical journey where every step matters. Master challenging parkour mechanics, defy gravity, and climb higher to discover what lies at the top.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-6600", ram: "8 GB RAM", gpu: "GTX 1650" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-8700", ram: "16 GB RAM", gpu: "RTX 3060" }
  },
  { 
    id: '998', 
    n: "Schedule 1", 
    dev: "Indie Dev", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=998&name=Schedule%201", 
    img: "https://static0.srcdn.com/wordpress/wp-content/uploads/sharedimages/2025/03/schedule-i-tag-page-cover-art.jpg?w=1200&h=900&fit=crop", 
    bg: "https://images.unsplash.com/photo-1506784951206-b96e42c2226f?w=1920&h=1080&fit=crop", 
    ach: 10, 
    tags: ["Adventure", "Mystery", "Indie"],
    desc: "Dive into a gripping indie adventure wrapped in mystery. Solve intricate puzzles, uncover hidden truths, and make decisions that will forever alter your fate.",
    rm: { os: "Windows 10", cpu: "Intel Core i3", ram: "4 GB RAM", gpu: "GTX 750" },
    rr: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1050" }
  },
  { 
    id: '996', 
    n: "RuneScape: Dragonwilds", 
    dev: "Jagex", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=996&name=RuneScape%3A%20Dragonwilds", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1343400/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1343400/library_hero.jpg", 
    ach: 100, 
    tags: ["MMORPG", "Fantasy", "Open World", "Adventure"],
    desc: "Enter the massive fantasy world of Gielinor. Train unique skills, complete epic quests, and battle legendary dragons in this beloved classic MMORPG.",
    rm: { os: "Windows 10", cpu: "Intel Core i3", ram: "4 GB RAM", gpu: "Integrated Graphics" },
    rr: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1050" }
  },
  { 
    id: '975', 
    n: "Poppy Playtime: Chapter 4", 
    dev: "Mob Entertainment", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=975&name=Poppy%20Playtime%3A%20Chapter%204", 
    img: "https://cdn1.epicgames.com/spt-assets/465c0f6c95d04b1c86b280b4925fee2d/poppy-playtime-1g4f9.jpg", 
    bg: "https://assets.nintendo.com/image/upload/q_auto/f_auto/store/software/switch/70010000085884/e4a283c588469fa52f058b0695b2c9ead24ed1f484e8f08ee29337210e7ef976", 
    ach: 15, 
    tags: ["Horror", "Puzzle", "Indie", "Adventure"],
    desc: "The terrifying saga continues as you descend deeper into the forgotten depths of Playtime Co. Outsmart new monstrous toys and uncover the darkest secrets yet.",
    rm: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 10", cpu: "Intel Core i7", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '974', 
    n: "Raft", 
    dev: "Redbeet Interactive", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=974&name=Raft", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/648800/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/648800/library_hero.jpg", 
    ach: 20, 
    tags: ["Survival", "Multiplayer", "Open World", "Crafting"],
    desc: "Thrown into an epic oceanic adventure alone or with friends, gather debris to survive, expand your floating home, and be wary of the dangers lurking beneath.",
    rm: { os: "Windows 7", cpu: "2.6 GHz Dual Core", ram: "4 GB RAM", gpu: "GTX 500" },
    rr: { os: "Windows 10", cpu: "Intel Core i5 2.6GHz", ram: "8 GB RAM", gpu: "GTX 750 Ti" }
  },
  { 
    id: '985', 
    n: "Football Manager 2023", 
    dev: "Sports Interactive", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=985&name=Football%20Manager%202023", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1904540/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1904540/library_hero.jpg", 
    ach: 50, 
    tags: ["Sports", "Management", "Simulation", "Strategy"],
    desc: "Build your dream squad, outsmart your rivals, and experience the thrill of massive European nights in the ultimate football management simulation.",
    rm: { os: "Windows 7", cpu: "Intel Core 2", ram: "4 GB RAM", gpu: "Intel GMA X4500" },
    rr: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 960" }
  },
  { 
    id: '980', 
    n: "Platform 8", 
    dev: "Chilla's Art", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=980&name=Platform%208", 
    img: "https://playism.com/wp-content/uploads/2024/11/06_8th_Logo_Keyart-1024x576.jpg", 
    bg: "https://playism.com/wp-content/uploads/2024/11/06_8th_Logo_Keyart-1024x576.jpg", 
    ach: 5, 
    tags: ["Horror", "Walking Sim", "Indie", "Atmospheric"],
    desc: "You are trapped on a mysterious, endlessly looping train. Keep your eyes peeled for any anomalies to find your way out in this tense psychological horror experience.",
    rm: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 10", cpu: "Intel Core i7", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '970', 
    n: "Uncharted 4", 
    dev: "Naughty Dog", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=970&name=Uncharted%204", 
    img: "https://preview.redd.it/i-made-this-uncharted-4-poster-v0-pg0s83b9l7p61.jpg?auto=webp&s=e2c84c3ef21742b2fd7da369394a0ce6b60ee0bd", 
    bg: "https://cdn.craft.cloud/22b11234-f633-4f7c-8ac2-099f2dba995c/assets/uploads/2014_06_09_U4_E3Trailer_Blog960x540.jpg?width=2048&height=1152&quality=82&fit=cover&s=dcTs0axzFcmfx3vmar92Sbl4wFXh00EpidQMmLpTlSY", 
    ach: 56, 
    tags: ["Action", "Adventure", "Story Rich", "Third-Person"],
    desc: "Forced back into the dangerous world of thieves, Nathan Drake embarks on a globe-trotting journey in pursuit of a historical conspiracy behind a fabled pirate treasure.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-4330", ram: "8 GB RAM", gpu: "GTX 960" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-4770", ram: "16 GB RAM", gpu: "RTX 2070" }
  },
  { 
    id: '995', 
    n: "Cities: Skylines 2", 
    dev: "Colossal Order", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=995&name=Cities%3A%20Skylines%202", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/949230/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/949230/library_hero.jpg", 
    ach: 40, 
    tags: ["Simulation", "City Builder", "Strategy", "Management"],
    desc: "Raise a city from the ground up and transform it into a thriving metropolis. The most realistic city builder ever brings deep simulation and a living economy.",
    rm: { os: "Windows 10", cpu: "Intel Core i7-6700K", ram: "8 GB RAM", gpu: "GTX 970" },
    rr: { os: "Windows 11", cpu: "Intel Core i5-12600K", ram: "16 GB RAM", gpu: "RTX 3080" }
  },
  { 
    id: '992', 
    n: "Frostpunk 2", 
    dev: "11 bit studios", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=992&name=Frostpunk%202", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1601580/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1601580/library_hero.jpg", 
    ach: 30, 
    tags: ["Survival", "Strategy", "City Builder", "Post-Apocalyptic"],
    desc: "Discover a city-survival game set 30 years after an apocalyptic blizzard. Guide your civilization through brutal choices, political turmoil, and freezing despair.",
    rm: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 11", cpu: "Intel Core i7", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '966', 
    n: "Poppy Playtime: Chapter 2", 
    dev: "Mob Entertainment", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=966&name=Poppy%20Playtime%3A%20Chapter%202", 
    img: "https://cdn1.epicgames.com/spt-assets/465c0f6c95d04b1c86b280b4925fee2d/poppy-playtime-1g3iv.png", 
    bg: "https://cdn1.epicgames.com/spt-assets/465c0f6c95d04b1c86b280b4925fee2d/poppy-playtime-75nij.png", 
    ach: 10, 
    tags: ["Horror", "Puzzle", "Indie"],
    desc: "Explore the massive Train Station and outsmart Mommy Long Legs. The abandoned toy factory continues to hold nightmarish secrets in this terrifying sequel.",
    rm: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 10", cpu: "Intel Core i7", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '965', 
    n: "Poppy Playtime: Chapter 1", 
    dev: "Mob Entertainment", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=965&name=Poppy%20Playtime%3A%20Chapter%201", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1721470/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1721470/library_hero.jpg", 
    ach: 5, 
    tags: ["Horror", "Puzzle", "Indie"],
    desc: "Survive the vengeful toys waiting for you in the abandoned toy factory. Use your GrabPack to hack electrical circuits and catch items from afar.",
    rm: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 10", cpu: "Intel Core i7", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '958', 
    n: "Poppy Playtime: Chapter 3", 
    dev: "Mob Entertainment", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=958&name=Poppy%20Playtime%3A%20Chapter%203", 
    img: "https://cdn.displate.com/artwork/857x1200/2026-01-29/51bf7d02-f692-4d5a-bb6d-6b8b01295343.jpg", 
    bg: "https://assets.nintendo.com/image/upload/q_auto/f_auto/store/software/switch/70010000080061/84d905b10cdc77d6c0e034b2047c0cadbd58c7dd5c6b3661057ea71b225aad20", 
    ach: 12, 
    tags: ["Horror", "Puzzle", "Indie"],
    desc: "Descend into Playcare, the dark, rotting orphanage hidden beneath the factory. Navigate blood-soaked halls and face off against CatNap in the most terrifying chapter yet.",
    rm: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 10", cpu: "Intel Core i7", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '973', 
    n: "Mafia III: Definitive Edition", 
    dev: "Hangar 13", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/
