const G_DATA = [
  { 
    id: '117', 
    n: "Cyberpunk 2077", 
    dev: "CD PROJEKT RED", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=117&name=Cyberpunk%202077", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_hero.jpg", 
    ach: 45, 
    tags: ["Cyberpunk", "Open World", "RPG", "Sci-fi"],
    desc: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a megalopolis obsessed with power, glamour, and body modification.",
    rm: { os: "Windows 10", cpu: "Intel Core i7-6700K", ram: "12 GB RAM", gpu: "GTX 1060 6GB" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-12700", ram: "16 GB RAM", gpu: "RTX 2060 SUPER" }
  },
  { 
    id: '209', 
    n: "Grand Theft Auto V", 
    dev: "Rockstar North", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=209", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_hero.jpg", 
    ach: 77, 
    tags: ["Open World", "Action", "Multiplayer", "Crime"],
    desc: "When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening elements of the criminal underworld.",
    rm: { os: "Windows 10 64 Bit", cpu: "Intel Core 2 Quad CPU", ram: "4 GB RAM", gpu: "NVIDIA 9800 GT 1GB" },
    rr: { os: "Windows 10 64 Bit", cpu: "Intel Core i5 3470", ram: "8 GB RAM", gpu: "NVIDIA GTX 660 2GB" }
  },
  { 
    id: '598', 
    n: "Elden Ring", 
    dev: "FromSoftware Inc.", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=598", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_hero.jpg", 
    ach: 42, 
    tags: ["Souls-like", "Dark Fantasy", "RPG", "Difficult"],
    desc: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    rm: { os: "Windows 10", cpu: "INTEL CORE I5-8400", ram: "12 GB RAM", gpu: "GTX 1060 3 GB" },
    rr: { os: "Windows 10/11", cpu: "INTEL CORE I7-8700K", ram: "16 GB RAM", gpu: "GTX 1070 8 GB" }
  },
  { 
    id: '1014', 
    n: "Sim Racing Telemetry - F1 22", 
    dev: "Codemasters", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1014&name=Sim%20Racing%20Telemetry%20-%20F1%2022", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1692250/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1692250/library_hero.jpg", 
    ach: 30, 
    tags: ["Racing", "Simulation", "Sports", "Formula 1"],
    desc: "Take your seat in the new era of Formula 1. Analyze deep telemetry and conquer the tracks of the 2022 FIA Formula One World Championship with unprecedented realism.",
    rm: { os: "Windows 10", cpu: "Intel Core i3-2130", ram: "8 GB RAM", gpu: "GTX 1050 Ti" },
    rr: { os: "Windows 10", cpu: "Intel Core i5 9600K", ram: "16 GB RAM", gpu: "GTX 1660 Ti" }
  },
  { 
    id: '1021', 
    n: "Little Nightmares III", 
    dev: "Supermassive Games", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1021&name=Little%20Nightmares%20III", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2136470/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2136470/library_hero.jpg", 
    ach: 25, 
    tags: ["Horror", "Puzzle", "Adventure", "Atmospheric"],
    desc: "Embark on a haunting cooperative journey. Navigate a surreal, disturbing world and face your deepest childhood fears to escape the Nowhere.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-8400", ram: "8 GB RAM", gpu: "GTX 1060" },
    rr: { os: "Windows 11", cpu: "Intel Core i7-9700", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '1018', 
    n: "SAND LAND", 
    dev: "ILCA, Inc.", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1018&name=SAND%20LAND", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1979440/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1979440/library_hero.jpg", 
    ach: 35, 
    tags: ["Action", "RPG", "Anime", "Open World"],
    desc: "Dive into a vast desert world where humans and demons suffer from extreme water shortages. Play as the Fiend Prince Beelzebub and lead a heroic misfit cast.",
    rm: { os: "Windows 10", cpu: "AMD FX-8350", ram: "4 GB RAM", gpu: "Radeon HD 7870" },
    rr: { os: "Windows 10", cpu: "Intel Core i5-9400", ram: "8 GB RAM", gpu: "GTX 1660" }
  },
  { 
    id: '1016', 
    n: "X-Plane 11", 
    dev: "Laminar Research", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1016&name=X-Plane%2011", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/269950/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/269950/library_hero.jpg", 
    ach: 0, 
    tags: ["Simulation", "Flight", "Realistic", "Open World"],
    desc: "Experience the ultimate in flight simulation. Featuring a highly detailed physics engine, pilot a massive variety of aircraft across a beautifully rendered globe.",
    rm: { os: "Windows 8", cpu: "Intel Core i3", ram: "8 GB RAM", gpu: "GTX 1050" },
    rr: { os: "Windows 10", cpu: "Intel Core i5 8600K", ram: "16 GB RAM", gpu: "GTX 1070" }
  },
   { 
    id: 'MC120', 
    n: "Minecraft 1.20 Browser (Eagler Craft)", 
    dev: "Some random dude", 
    url: "https://yee.pages.dev/#/bW9yZS9tb3JlL21vZGRlZC9lYWdseWpz",
    img: "https://cdn.mos.cms.futurecdn.net/AZ4nyhrARyZhc69hMXAy3L.jpg",
    bg: "https://cdn.mos.cms.futurecdn.net/AZ4nyhrARyZhc69hMXAy3L.jpg",
    ach: 45, 
    tags: ["Minecraft", "Open World", "RPG", "Sci-fi"],
    desc: "Minecraft is a critically acclaimed 3D sandbox video game developed by the Swedish studio Mojang Studios. It has no specific goals, offering players absolute freedom to explore, build, and craft. The game world is made of 3D blocks representing materials like dirt, stone, and wood.",
    rm: { os: "Potato", cpu: "Potato", ram: "Potato", gpu: "Potato" },
    rr: { os: "Monster", cpu: "Monster", ram: "Monster", gpu: "Monster" }
  },
  { 
    id: '1015', 
    n: "GUILTY GEAR -STRIVE-", 
    dev: "Arc System Works", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1015&name=GUILTY%20GEAR%20-STRIVE-", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1384160/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1384160/library_hero.jpg", 
    ach: 40, 
    tags: ["Fighting", "Action", "Anime", "2D"],
    desc: "Experience the cutting edge of 2D fighting games. With stunning cel-shaded visuals and an explosive heavy-metal soundtrack, prepare for intense, high-octane combat.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-3450", ram: "4 GB RAM", gpu: "GTX 650 Ti" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-3770", ram: "8 GB RAM", gpu: "GTX 660" }
  },
  { 
    id: '1013', 
    n: "Clair Obscur: Expedition 33", 
    dev: "Sandfall Interactive", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1013&name=Clair%20Obscur%3A%20Expedition%2033", 
    img: "https://cdn1.epicgames.com/spt-assets/330dace5ffc74156987f91d454ac544b/project-w-1kt2x.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2808040/library_hero.jpg", 
    ach: 20, 
    tags: ["RPG", "Turn-Based", "Fantasy", "Story Rich"],
    desc: "A breathtaking turn-based RPG with real-time mechanics. Join Expedition 33 and break the deadly cycle of the Paintress before she erases humanity.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-8400", ram: "12 GB RAM", gpu: "GTX 1070" },
    rr: { os: "Windows 11", cpu: "Intel Core i7-10700K", ram: "16 GB RAM", gpu: "RTX 3060" }
  },
  { 
    id: '1012', 
    n: "Easy Red 2", 
    dev: "Marco Amadei", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1012&name=Easy%20Red%202", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1325710/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1325710/library_hero.jpg", 
    ach: 30, 
    tags: ["Shooter", "WWII", "Action", "Simulation"],
    desc: "Experience the massive scale of World War II. Fight in historical battles with an emphasis on tactical realism, squad management, and massive maps.",
    rm: { os: "Windows 7", cpu: "Intel Core i3", ram: "4 GB RAM", gpu: "GTX 460" },
    rr: { os: "Windows 10", cpu: "Intel Core i5", ram: "8 GB RAM", gpu: "GTX 960" }
  },
  { 
    id: '1003', 
    n: "JDM: Japanese Drift Master", 
    dev: "Gaming Factory", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1003&name=JDM%3A%20Japanese%20Drift%20Master", 
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1153410/library_600x900.jpg", 
    bg: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1153410/library_hero.jpg", 
    ach: 15, 
    tags: ["Racing", "Drifting", "Automobile", "Simulation"],
    desc: "Discover the heart of Japanese automotive culture. Drift through beautifully recreated streets, tune your vehicles, and master the art of the perfect slide.",
    rm: { os: "Windows 10", cpu: "Intel Core i5-4460", ram: "8 GB RAM", gpu: "GTX 1050" },
    rr: { os: "Windows 10", cpu: "Intel Core i7-7700", ram: "16 GB RAM", gpu: "RTX 2060" }
  },
  { 
    id: '1002', 
    n: "The First Berserker: Khazan", 
    dev: "Nexon", 
    url: "https://www.raccoongame.com/wap/dist/#/platform/cloudgame/gamedetail?gid=1002&name=The%20First%20Berserker%3A
